version: 2.1

jobs:
  build:
    docker:
      - image: afonsoaugusto/base-ci:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: |
            make build
      - run:
          name: scan
          command: |
            make scan            
      - run:
          name: publish
          command: |
            make publish

workflows:
  workflow:
    jobs:
      - build:
          context: CI